name: Argus Eye

on:
  # schedule:
    # - cron: '0 0 * * *'

  workflow_dispatch:

job:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Run Telegram Test Script
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        RESEARCH_TOPIC: ${{ secrets.RESEARCH_TOPIC }}
        RESEARCH_URLS: ${{ secrets.RESEARCH_URLS }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: node index.mjs